### ISSUE TITLE
No such file or directory: 'requirements.txt' & No module named 'ndb' in "nutrition_us_ndb-checkpoint."

### ISSUE THREAD

**Issue by liandy52** [chanvarma/proj4-eep153sp19-holbrook-working#12]
File unable to be located.

**Comment by chanvarma** [comment]
Thanks for pointing this out. The error is fixed, and you can run the updated code by following the instructions under the 'Start here' section of the read-me linked below.

[Read me](https://github.com/chanvarma/proj4-eep153sp19-holbrook-working/blob/master/README.md )
