### ISSUE TITLE
CFE file not in respository

### ISSUE THREAD

**Issue by nathanorwig** [chanvarma/proj4-eep153sp19-holbrook-working#2]
When trying to run Working Code -- Proj 4-checkpoint it does not work because the CFE file is not found. Because it was created by Professor Ligon, I believe you have to also upload that file to the folder in order for us to run it. To do so you can go to the this class' on jupyter notebook and download file from the Hacking Food Nutrition

**Comment by nathanorwig** [comment]
Also there are missing files such that I cannot run the code 
<img width="654" alt="Screen Shot 2019-05-01 at 2 39 10 PM" src="https://user-images.githubusercontent.com/35481199/57044267-e6e38580-6c1e-11e9-88c8-3dea9bdc87f3.png">

**Comment by sannidhishukla** [comment]
What notebook is this in?

**Comment by chanvarma** [comment]
Thanks for pointing this out. The error is fixed, and you can run the updated code by following the instructions under the 'Start here' section of the read-me linked below.

[Read me](https://github.com/chanvarma/proj4-eep153sp19-holbrook-working/blob/master/README.md )
