### ISSUE TITLE
No such file or directory: '../data/' in "Chan's Working Copy-checkpoint"

### ISSUE THREAD

**Issue by liandy52** [chanvarma/proj4-eep153sp19-holbrook-working#6]
I'm unsure about the reference for this file.

**Comment by chanvarma** [comment]
Thanks for pointing this out. The error is fixed, and you can run the updated code by following the instructions under the 'Start here' section of the read-me linked below.

[Read me](https://github.com/chanvarma/proj4-eep153sp19-holbrook-working/blob/master/README.md )
