### ISSUE TITLE
File b'../data/actual/no_food_stamps.csv' does not exist in "Project 4 | Submission copy-checkpoint."

### ISSUE THREAD

**Issue by liandy52** [chanvarma/proj4-eep153sp19-holbrook-working#7]
File unable to be located.

**Comment by chanvarma** [comment]
Fixed. Please reload https://github.com/chanvarma/proj4-eep153sp19-holbrook-working/blob/master/code/Project%204%20%7C%20Presentation%20Ready.ipynb to see updated code.
