### ISSUE TITLE
File b'../data/actual/no_food_stamps.csv' does not exist in "Working Code -- Proj 4-checkpoint."

### ISSUE THREAD

**Issue by liandy52** [chanvarma/proj4-eep153sp19-holbrook-working#8]
File unable to be located.

**Comment by chanvarma** [comment]
Thanks for pointing this out. The error is fixed, and you can run the updated code by following the instructions under the 'Start here' section of the read-me linked below.

[Read me](https://github.com/chanvarma/proj4-eep153sp19-holbrook-working/blob/master/README.md )
