### ISSUE TITLE
Working Code Proj 4 Notebook

### ISSUE THREAD

**Issue by harcourt-rebecca** [chanvarma/proj4-eep153sp19-holbrook-working#9]
<img width="908" alt="Screen Shot 2019-05-01 at 3 26 40 PM" src="https://user-images.githubusercontent.com/46976436/57046508-a2a7b380-6c25-11e9-956b-2ddba278b169.png">
<img width="954" alt="Screen Shot 2019-05-01 at 3 26 52 PM" src="https://user-images.githubusercontent.com/46976436/57046510-a4717700-6c25-11e9-8b57-22fd1b6e2aea.png">
<img width="945" alt="Screen Shot 2019-05-01 at 3 26 58 PM" src="https://user-images.githubusercontent.com/46976436/57046523-b05d3900-6c25-11e9-9e6f-208240e39792.png">

Hi not sure why I can't run these cells. It seems like you referenced the names before you created them.

**Comment by chanvarma** [comment]
Thanks for pointing this out. The error is fixed, and you can run the updated code by following the instructions under the 'Start here' section of the read-me linked below.

[Read me](https://github.com/chanvarma/proj4-eep153sp19-holbrook-working/blob/master/README.md )
